hosts: all
remote_user: ec2-user
become: yes
tasks:
 - name: installing ....
   yum:
      name: "{{ packages }}"
      state: present
      packages:
        - php
        - mysql
        - unzip